import { Buffer } from "node:buffer";
import { inflateRawSync } from "node:zlib";

export interface ZipEntry {
  path: string;
  data: Buffer;
}

export function compareCodeUnitStrings(left: string, right: string): number {
  if (left === right) return 0;
  return left < right ? -1 : 1;
}

const CRC_TABLE = Array.from({ length: 256 }, (_, index) => {
  let value = index;
  for (let bit = 0; bit < 8; bit += 1) value = (value & 1) !== 0 ? 0xedb88320 ^ (value >>> 1) : value >>> 1;
  return value >>> 0;
});

function crc32(data: Buffer): number {
  let crc = 0xffffffff;
  for (const byte of data) crc = CRC_TABLE[(crc ^ byte) & 0xff] ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}

function localHeader(name: Buffer, data: Buffer, crc: number): Buffer {
  const header = Buffer.alloc(30);
  header.writeUInt32LE(0x04034b50, 0);
  header.writeUInt16LE(20, 4);
  header.writeUInt16LE(0x0800, 6);
  header.writeUInt16LE(0, 8);
  header.writeUInt16LE(0, 10);
  header.writeUInt16LE(33, 12);
  header.writeUInt32LE(crc, 14);
  header.writeUInt32LE(data.length, 18);
  header.writeUInt32LE(data.length, 22);
  header.writeUInt16LE(name.length, 26);
  return Buffer.concat([header, name]);
}

function centralHeader(name: Buffer, data: Buffer, crc: number, offset: number): Buffer {
  const header = Buffer.alloc(46);
  header.writeUInt32LE(0x02014b50, 0);
  header.writeUInt16LE(0x0314, 4);
  header.writeUInt16LE(20, 6);
  header.writeUInt16LE(0x0800, 8);
  header.writeUInt16LE(0, 10);
  header.writeUInt16LE(0, 12);
  header.writeUInt16LE(33, 14);
  header.writeUInt32LE(crc, 16);
  header.writeUInt32LE(data.length, 20);
  header.writeUInt32LE(data.length, 24);
  header.writeUInt16LE(name.length, 28);
  header.writeUInt32LE((0o100644 << 16) >>> 0, 38);
  header.writeUInt32LE(offset, 42);
  return Buffer.concat([header, name]);
}

export function createZip(entries: ZipEntry[]): Buffer {
  const localParts: Buffer[] = [];
  const centralParts: Buffer[] = [];
  let offset = 0;

  for (const entry of [...entries].sort((a, b) => compareCodeUnitStrings(a.path, b.path))) {
    const name = Buffer.from(entry.path, "utf8");
    const crc = crc32(entry.data);
    const local = localHeader(name, entry.data, crc);
    localParts.push(local, entry.data);
    centralParts.push(centralHeader(name, entry.data, crc, offset));
    offset += local.length + entry.data.length;
  }

  const central = Buffer.concat(centralParts);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(central.length, 12);
  end.writeUInt32LE(offset, 16);
  return Buffer.concat([...localParts, central, end]);
}

/**
 * Reads one entry from the store/deflate ZIPs generated by this project.
 * The management API uses this to verify that metadata and the archive's
 * manifest describe the same plugin before anything is published.
 */
export function readZipEntry(archive: Buffer, entryPath: string): Buffer | null {
  if (archive.length < 22) throw new Error("archive is not a valid ZIP");
  const minimumEndOffset = Math.max(0, archive.length - 22 - 0xffff);
  let endOffset = -1;
  for (let offset = archive.length - 22; offset >= minimumEndOffset; offset -= 1) {
    if (archive.readUInt32LE(offset) === 0x06054b50) {
      endOffset = offset;
      break;
    }
  }
  if (endOffset < 0) throw new Error("archive is not a valid ZIP");

  const entryCount = archive.readUInt16LE(endOffset + 10);
  const centralSize = archive.readUInt32LE(endOffset + 12);
  const centralOffset = archive.readUInt32LE(endOffset + 16);
  if (centralOffset + centralSize > archive.length) throw new Error("ZIP central directory is truncated");

  let offset = centralOffset;
  for (let index = 0; index < entryCount; index += 1) {
    if (offset + 46 > archive.length || archive.readUInt32LE(offset) !== 0x02014b50) {
      throw new Error("ZIP central directory entry is invalid");
    }
    const method = archive.readUInt16LE(offset + 10);
    const flags = archive.readUInt16LE(offset + 8);
    const compressedSize = archive.readUInt32LE(offset + 20);
    const uncompressedSize = archive.readUInt32LE(offset + 24);
    const nameSize = archive.readUInt16LE(offset + 28);
    const extraSize = archive.readUInt16LE(offset + 30);
    const commentSize = archive.readUInt16LE(offset + 32);
    const localOffset = archive.readUInt32LE(offset + 42);
    const nameStart = offset + 46;
    const nextOffset = nameStart + nameSize + extraSize + commentSize;
    if (nextOffset > archive.length) throw new Error("ZIP central directory entry is truncated");
    const name = archive.subarray(nameStart, nameStart + nameSize).toString("utf8");
    if (name === entryPath) {
      if ((flags & 0x1) !== 0) throw new Error("encrypted ZIP entries are not supported");
      if (localOffset + 30 > archive.length || archive.readUInt32LE(localOffset) !== 0x04034b50) {
        throw new Error("ZIP local entry is invalid");
      }
      const localNameSize = archive.readUInt16LE(localOffset + 26);
      const localExtraSize = archive.readUInt16LE(localOffset + 28);
      const dataStart = localOffset + 30 + localNameSize + localExtraSize;
      const dataEnd = dataStart + compressedSize;
      if (dataEnd > archive.length) throw new Error("ZIP entry data is truncated");
      const compressed = archive.subarray(dataStart, dataEnd);
      const data = method === 0 ? Buffer.from(compressed) : method === 8 ? inflateRawSync(compressed) : null;
      if (!data) throw new Error(`ZIP compression method ${method} is not supported`);
      if (data.length !== uncompressedSize) throw new Error("ZIP entry size does not match its header");
      return data;
    }
    offset = nextOffset;
  }
  return null;
}
